# Generated by Django 5.1.15 on 2026-08-08 18:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_core', '0002_clase_materia_horario_seccion_materia_seccion_and_more'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la evaluación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la tarea o examen')),
                ('fecha', models.DateField(verbose_name='Fecha de aplicación')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje dentro del TipoNota')),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Nota Máxima')),
                ('es_examen', models.BooleanField(default=False, verbose_name='¿Es Examen?')),
                ('es_reparacion', models.BooleanField(default=False, verbose_name='¿Es Reparación / Convocatoria Extraordinaria?')),
                ('publicada', models.BooleanField(default=True, verbose_name='Publicada')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academic_core.materia', verbose_name='Materia')),
                ('tipo_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academic_core.tiponota', verbose_name='Tipo de Nota')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['materia', 'tipo_nota', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado / Nota (Decimal 5,2)')),
                ('literal', models.CharField(blank=True, max_length=10, verbose_name='Literal (Escala Cualitativa)')),
                ('es_consolidado', models.BooleanField(default=False, help_text='Indica si esta nota es el cálculo agregado de evaluaciones/consolidados inferiores.', verbose_name='¿Es una nota consolidada?')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='Observación / Comentario')),
                ('calificacion_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desglosadas', to='grading.calificacion', verbose_name='Nota Consolidada Padre')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='people.estudiante', verbose_name='Estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academic_core.materia', verbose_name='Materia')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
                ('tipo_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academic_core.tiponota', verbose_name='Tipo de Nota')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='grading.evaluacion', verbose_name='Evaluación de origen')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['materia', 'estudiante', 'tipo_nota'],
            },
        ),
        migrations.CreateModel(
            name='ResumenAcademicoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promedio General Acumulado')),
                ('materias_reprobadas', models.PositiveIntegerField(default=0, verbose_name='Número de materias reprobadas')),
                ('materias_reparadas', models.PositiveIntegerField(default=0, verbose_name='Número de materias en reparación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_academicos', to='people.estudiante', verbose_name='Estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes_academicos', to='academic_core.periodolectivo', verbose_name='Período Lectivo')),
            ],
            options={
                'verbose_name': 'Resumen Académico de Estudiante',
                'verbose_name_plural': 'Resúmenes Académicos de Estudiantes',
                'unique_together': {('estudiante', 'periodo')},
            },
        ),
    ]
