# Generated by Django 5.1.15 on 2026-08-08 17:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_core', '0002_clase_materia_horario_seccion_materia_seccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=50, unique=True, verbose_name='Código de empleado')),
                ('especialidad', models.CharField(blank=True, max_length=150, verbose_name='Especialidad o área principal')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de residencia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/fotos/', verbose_name='Fotografía')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso')),
            ],
            options={
                'verbose_name': 'Docente / Profesor',
                'verbose_name_plural': 'Docentes / Profesores',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=50, unique=True, verbose_name='Código de estudiante (Carnet)')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('cedula_identidad', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cédula / Identificación')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/', verbose_name='Fotografía')),
                ('activo', models.BooleanField(default=True, verbose_name='Estudiante Activo')),
                ('retirado', models.BooleanField(default=False, verbose_name='Estado Retirado')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('motivo_retiro', models.TextField(blank=True, verbose_name='Motivo de retiro')),
                ('escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.escolaridad', verbose_name='Escolaridad de Origen')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.estadocivil', verbose_name='Estado Civil')),
                ('recorrido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.recorrido', verbose_name='Ruta de Transporte')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_core.religion', verbose_name='Religión')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['primer_apellido', 'primer_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título o Grado Obtenido')),
                ('institucion', models.CharField(max_length=150, verbose_name='Institución Educativa')),
                ('fecha_obtencion', models.DateField(blank=True, null=True, verbose_name='Fecha de Obtención')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudio / Título Academic',
                'verbose_name_plural': 'Estudios / Títulos Académicos',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo o Puesto')),
                ('institucion', models.CharField(max_length=150, verbose_name='Empresa u Organización')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_empleado', models.CharField(db_index=True, max_length=50, verbose_name='Código de empleado')),
                ('especialidad', models.CharField(blank=True, max_length=150, verbose_name='Especialidad o área principal')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de residencia')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='Fotografía')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso')),
            ],
            options={
                'verbose_name': 'historical Docente / Profesor',
                'verbose_name_plural': 'historical Docentes / Profesores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEstudiante',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(db_index=True, max_length=50, verbose_name='Código de estudiante (Carnet)')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('cedula_identidad', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Cédula / Identificación')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='Fotografía')),
                ('activo', models.BooleanField(default=True, verbose_name='Estudiante Activo')),
                ('retirado', models.BooleanField(default=False, verbose_name='Estado Retirado')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('motivo_retiro', models.TextField(blank=True, verbose_name='Motivo de retiro')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('escolaridad', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academic_core.escolaridad', verbose_name='Escolaridad de Origen')),
                ('estado_civil', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academic_core.estadocivil', verbose_name='Estado Civil')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorrido', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academic_core.recorrido', verbose_name='Ruta de Transporte')),
                ('religion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academic_core.religion', verbose_name='Religión')),
            ],
            options={
                'verbose_name': 'historical Estudiante',
                'verbose_name_plural': 'historical Estudiantes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPariente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('cedula_identidad', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Cédula de identidad')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor Legal'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('OTRO', 'Otro')], max_length=50, verbose_name='Relación / Parentesco')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de residencia')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=150, verbose_name='Lugar de trabajo')),
                ('profesion', models.CharField(blank=True, max_length=100, verbose_name='Profesión u ocupación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso (Opcional)')),
            ],
            options={
                'verbose_name': 'historical Pariente / Tutor',
                'verbose_name_plural': 'historical Parientes / Tutores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pariente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo apellido')),
                ('cedula_identidad', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Cédula de identidad')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor Legal'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('OTRO', 'Otro')], max_length=50, verbose_name='Relación / Parentesco')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de residencia')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=150, verbose_name='Lugar de trabajo')),
                ('profesion', models.CharField(blank=True, max_length=100, verbose_name='Profesión u ocupación')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_pariente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso (Opcional)')),
            ],
            options={
                'verbose_name': 'Pariente / Tutor',
                'verbose_name_plural': 'Parientes / Tutores',
            },
        ),
        migrations.CreateModel(
            name='EstudianteClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado', models.CharField(choices=[('INSCRITO', 'Inscrito Normal'), ('TRASLADADO', 'Trasladado de Sección'), ('RETIRADO', 'Retirado'), ('REPITENTE', 'Repitente')], default='INSCRITO', max_length=20, verbose_name='Estado de Matrícula')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_inscritos', to='academic_core.clase', verbose_name='Clase / Grado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='people.estudiante', verbose_name='Estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academic_core.periodolectivo', verbose_name='Período Lectivo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_inscritos', to='academic_core.seccion', verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Matrícula de Estudiante (EstudianteClase)',
                'verbose_name_plural': 'Matrículas de Estudiantes',
                'unique_together': {('estudiante', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_representante_legal', models.BooleanField(default=True, verbose_name='Es Representante Legal')),
                ('es_responsable_financiero', models.BooleanField(default=True, verbose_name='Es Responsable Financiero')),
                ('convive_con_estudiante', models.BooleanField(default=True, verbose_name='Convive con el estudiante')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='people.estudiante', verbose_name='Estudiante')),
                ('pariente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_a_cargo', to='people.pariente', verbose_name='Pariente / Tutor')),
            ],
            options={
                'verbose_name': 'Responsable de Estudiante',
                'verbose_name_plural': 'Responsables de Estudiantes',
                'unique_together': {('estudiante', 'pariente')},
            },
        ),
    ]
