# Generated by Django 5.1.15 on 2026-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto_normal',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/normal/', verbose_name='Fotografía (Normal 375x500)'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/thumb/', verbose_name='Fotografía (Miniatura 75x100)'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='foto_normal',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Fotografía (Normal 375x500)'),
        ),
        migrations.AddField(
            model_name='historicalestudiante',
            name='foto_thumb',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Fotografía (Miniatura 75x100)'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/fotos/', verbose_name='Fotografía (Original 600x800)'),
        ),
        migrations.AlterField(
            model_name='historicalestudiante',
            name='foto',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Fotografía (Original 600x800)'),
        ),
    ]
