# Generated by Django 5.1.15 on 2026-08-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_estudiante_foto_normal_estudiante_foto_thumb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('O+', 'O Positivo (O+)'), ('O-', 'O Negativo (O-)'), ('A+', 'A Positivo (A+)'), ('A-', 'A Negativo (A-)'), ('B+', 'B Positivo (B+)'), ('B-', 'B Negativo (B-)'), ('AB+', 'AB Positivo (AB+)'), ('AB-', 'AB Negativo (AB-)')], max_length=5, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias a Medicamentos o Alimentos')),
                ('padecimientos_cronicos', models.TextField(blank=True, verbose_name='Padecimientos o Enfermedades Crónicas')),
                ('medicamentos_permanentes', models.TextField(blank=True, verbose_name='Medicamentos de Uso Permanente')),
                ('seguro_medico', models.CharField(blank=True, max_length=150, verbose_name='Compañía de Seguro Médico')),
                ('numero_poliza', models.CharField(blank=True, max_length=50, verbose_name='Número de Póliza / Carnet')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=150, verbose_name='Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono de Emergencia')),
                ('autoriza_traslado_hospital', models.BooleanField(default=True, verbose_name='Autoriza Traslado Hospitalario de Emergencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Médicas y Restricciones Físicas')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='people.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Ficha Médica y de Salud',
                'verbose_name_plural': 'Fichas Médicas',
            },
        ),
    ]
