# Generated by Django 5.1.15 on 2026-08-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Sistema de Gestión Estudiantil THOT', max_length=150, verbose_name='Nombre de la Institución')),
                ('lema', models.CharField(blank=True, max_length=200, verbose_name='Lema o Eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institucion/logos/', verbose_name='Logo Institucional')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección de la Institución')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Institucional')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico Oficial')),
                ('pie_de_pagina_boletin', models.TextField(default='Documento Oficial de Calificaciones - Impreso desde el Sistema de Gestión Estudiantil.', verbose_name='Pie de página para Boletines y Reportes')),
            ],
            options={
                'verbose_name': 'Configuración Institucional (Marca Blanca)',
                'verbose_name_plural': 'Configuraciones Institucionales',
            },
        ),
    ]
 