# Generated by Django 5.1.15 on 2026-08-08 17:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de asignatura')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de asignatura')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la escala')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('escala', models.JSONField(blank=True, default=dict, help_text="Ejemplo: {'A': [90, 100], 'B': [80, 89], 'C': [60, 79], 'F': [0, 59]}", verbose_name='Estructura de la escala (Rangos o Literales)')),
                ('nota_minima_aprobatoria', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5, verbose_name='Nota mínima aprobatoria')),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, verbose_name='Nota máxima')),
            ],
            options={
                'verbose_name': 'Escala de Calificación',
                'verbose_name_plural': 'Escalas de Calificación',
            },
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del nivel')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código de nivel')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden jerárquico')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración heredable')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=False, help_text='Marque como activo si es el período lectivo corriente del colegio.', verbose_name='Activo')),
                ('abierto', models.BooleanField(default=True, help_text='Si está cerrado, se bloquea el ingreso de calificaciones.', verbose_name='Abierto a modificaciones')),
                ('visible', models.BooleanField(default=True, help_text='Controla si el período es visible en la interfaz para alumnos/padres.', verbose_name='Visible a usuarios')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración heredable del período')),
            ],
            options={
                'verbose_name': 'Período Lectivo',
                'verbose_name_plural': 'Períodos Lectivos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Recorrido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del recorrido / ruta')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de ruta')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o ruta detallada')),
            ],
            options={
                'verbose_name': 'Recorrido',
                'verbose_name_plural': 'Recorridos',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Religión',
                'verbose_name_plural': 'Religiones',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo de nota')),
                ('es_consolidado', models.BooleanField(default=False, help_text='Indica si este tipo de nota se calcula agregando las notas hijas.', verbose_name='Es un consolidado')),
                ('orden', models.PositiveIntegerField(default=1, verbose_name='Orden de secuencia')),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Peso')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje acumulado')),
                ('numero_consolidados', models.PositiveIntegerField(default=0, verbose_name='Número de consolidados')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración adicional')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='academic_core.tiponota', verbose_name='Tipo Nota Padre')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_notas', to='academic_core.periodolectivo', verbose_name='Período Lectivo')),
            ],
            options={
                'verbose_name': 'Tipo de Nota',
                'verbose_name_plural': 'Tipos de Nota',
                'ordering': ['periodo', 'orden'],
            },
        ),
    ]
