# Generated by Django 5.1.15 on 2026-08-08 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la clase')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración de la clase')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academic_core.nivel', verbose_name='Nivel Educativo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='academic_core.periodolectivo', verbose_name='Período Lectivo')),
            ],
            options={
                'verbose_name': 'Clase / Grado',
                'verbose_name_plural': 'Clases / Grados',
                'ordering': ['periodo', 'nivel__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre descriptivo de la materia')),
                ('lock_version', models.IntegerField(default=0, help_text='Controla actualizaciones concurrentes para evitar sobrescrituras accidentales.', verbose_name='Versión de Bloqueo Optimista')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Configuración específica de la materia')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academic_core.asignatura', verbose_name='Asignatura Base')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academic_core.clase', verbose_name='Clase / Grado')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_impartidas', to=settings.AUTH_USER_MODEL, verbose_name='Docente Titular')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['clase', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('aula', models.CharField(blank=True, max_length=50, verbose_name='Aula o espacio físico')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academic_core.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de sección')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de sección')),
                ('capacidad_maxima', models.PositiveIntegerField(default=40, verbose_name='Capacidad máxima de estudiantes')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='academic_core.clase', verbose_name='Clase / Grado')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['clase', 'codigo'],
                'unique_together': {('clase', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='academic_core.seccion', verbose_name='Sección específica'),
        ),
        migrations.CreateModel(
            name='DocenteMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=True, verbose_name='¿Es titular?')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_materias', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docentes', to='academic_core.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Docente por Materia',
                'verbose_name_plural': 'Docentes por Materia',
                'unique_together': {('materia', 'docente')},
            },
        ),
    ]
