# Generated by Django 5.1.15 on 2026-08-26 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_core', '0002_clase_materia_horario_seccion_materia_seccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='docente',
            field=models.ForeignKey(blank=True, help_text='Profesor guía responsable de la sección (equivalente a secciones.docente_id en Rails).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_como_guia', to=settings.AUTH_USER_MODEL, verbose_name='Docente Guía'),
        ),
    ]
