# Generated by Django 5.1.15 on 2026-08-08 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_core', '0002_clase_materia_horario_seccion_materia_seccion_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='support/adjuntos/', verbose_name='Archivo Adjunto')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original del Archivo')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha del suceso')),
                ('tipo_incidencia', models.CharField(choices=[('LEVE', 'Falta Leve'), ('GRAVE', 'Falta Grave'), ('VERY_GRAVE', 'Falta Muy Grave'), ('MERITO', 'Mérito / Reconocimiento')], default='LEVE', max_length=20, verbose_name='Tipo de Incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada de la incidencia')),
                ('sancion', models.TextField(blank=True, verbose_name='Sanción o medidas tomadas')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='people.estudiante', verbose_name='Estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='academic_core.periodolectivo', verbose_name='Período Lectivo')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado Por')),
            ],
            options={
                'verbose_name': 'Incidencia Disciplinaria / Mérito',
                'verbose_name_plural': 'Incidencias / Méritos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de envío')),
                ('ambito_destinatario', models.CharField(choices=[('GLOBAL', 'Todos los Usuarios'), ('PERIODO', 'Todo el Período Lectivo'), ('NIVEL', 'Por Nivel Educativo'), ('CLASE', 'Por Clase / Grado'), ('SECCION', 'Por Sección'), ('USUARIO', 'Usuario Específico')], default='USUARIO', max_length=30, verbose_name='Ámbito de Destino')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de objeto destino')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de objeto destino')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje Interno',
                'verbose_name_plural': 'Mensajes Internos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=10, verbose_name='Grupo Sanguíneo / RH')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('padecimientos', models.TextField(blank=True, verbose_name='Padecimientos o condiciones crónicas')),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos requeridos o autorizados')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150, verbose_name='Nombre de contacto de emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=30, verbose_name='Teléfono de emergencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones adicionales de salud')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_medico', to='people.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Registro Médico / Ficha de Salud',
                'verbose_name_plural': 'Registros Médicos',
            },
        ),
    ]
