# Generated by Django 5.1.15 on 2026-08-28 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_delete_registromedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_leido', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='support.mensaje', verbose_name='Mensaje')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destinatario')),
            ],
            options={
                'verbose_name': 'Mensaje por Usuario',
                'verbose_name_plural': 'Mensajes por Usuario',
                'unique_together': {('mensaje', 'usuario')},
            },
        ),
    ]
