# Generated by Django 5.1.15 on 2026-08-08 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('username_log', models.CharField(blank=True, help_text='Útil cuando la acción falla o es un intento de login de un usuario inexistente', max_length=150, verbose_name='Nombre de usuario registrado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('accion', models.CharField(db_index=True, max_length=100, verbose_name='Acción / Evento')),
                ('origen', models.CharField(choices=[('WEB', 'Petición Web'), ('CELERY', 'Tarea Asíncrona (Celery)'), ('CLI', 'Comando de Consola / ETL')], default='WEB', max_length=20, verbose_name='Origen de ejecución')),
                ('objeto_tipo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de objeto afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=100, verbose_name='ID de objeto afectado')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o detalle descriptivo')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Metadatos JSON (Sanitizados)')),
                ('exito', models.BooleanField(default=True, verbose_name='¿Ejecución Exitosa?')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Bitácora Global de Auditoría (AuditEvent)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
