# Generated by Django 5.1.15 on 2026-08-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='origen',
            field=models.CharField(choices=[('WEB', 'Petición Web'), ('CELERY', 'Tarea Asíncrona (Celery)'), ('CLI', 'Comando de Consola / ETL'), ('SISTEMA', 'Sistema / Señales Internas')], default='WEB', max_length=20, verbose_name='Origen de ejecución'),
        ),
    ]
